### ISSUE TITLE
Gray box component padding/margin issues

### ISSUE THREAD

**Issue by finance-nyc-harper** [nycdigitalservice/dof-design-system#2]
There are some issues with padding and margin on the gray box component

**Comment by finance-nyc-harper** [comment]
![content-box-bug](https://github.com/nycdigitalservice/dof-design-system/assets/142430419/9a385c93-516a-4bf1-8ab3-319ab797f061)

**Comment by mmausler-oti** [comment]
@finance-nyc-harper I'm looking at the [Dividing and Merging Lots page](https://nycgov-csg.cityapps.nycnet/site/finance2/property/property-dividing-and-merging-lots.page) and it doesn't seem like this section is using the alert component you've linked to. The `div` for this section is currently using inline CSS

![image](https://github.com/nycdigitalservice/dof-design-system/assets/108476568/84bea4d3-9dbe-4895-8f4e-aa1bc443eaaf)

Adding the `.alert` class produces the below

![image](https://github.com/nycdigitalservice/dof-design-system/assets/108476568/f54c17c8-98ab-4799-bc50-8dbc1a86736c)

If the `.alert` colored sidebar doesn't make sense for this section we should discuss in the next design meeting adding a new component (or an alert variation) that doesn't include the colored sidebar.

**Comment by finance-nyc-harper** [comment]
Understood, thank you!
